apiVersion: kcpaved.test.crossplane.io/v1alpha1
kind: KafkaSecret
metadata:
  name: kafkasecret-datalake
spec:
  forProvider:
    namespace: test-datalake-namespace
    apiEndPoint: vkm.ps.idps.a.intuit.com
    policyId: p-01klfv6dn26n
    truststoreCertPath: eventbus/cluster/ebus_datalake_uw2_e2e/truststore_ca.crt
  providerConfigRef:
    name: test-provider-config-idp-spp-dl-ppd-usw2-k8s