apiVersion: kcpaved.test.crossplane.io/v1alpha1
kind: KafkaSecret
metadata:
  name: kafkasecret-swimlane
spec:
  forProvider:
    namespace: test-swimlane-namespace
    apiEndPoint: vkm.ps.idps.a.intuit.com
    policyId: p-01klfv6dn26n
    truststoreCertPath: eventbus/cluster/ebus_sbseg_sl_uw2-e2e/truststore_ca.crt
    keystoreKeyPath: eventbus/cluster/ebus_sbseg_sl_uw2-e2e/keystore_key.pem
    keystoreCertPath: eventbus/cluster/ebus_sbseg_sl_uw2-e2e/keystore_crt.pem
  providerConfigRef:
    name: test-provider-config-idp-spp-dl-ppd-usw2-k8s